-- Implicit many-to-many join between UserContent and Tag (relation "UserContentTags").
--
-- Generated by `prisma migrate dev`. Two `DROP INDEX` statements it also emitted
-- have been removed:
--
--   DROP INDEX "LocalizedProfileField_value_trgm_idx";
--   DROP INDEX "UserContent_content_trgm_idx";
--
-- Those are the pg_trgm GIN indexes created by 20260415000000_add_custom_indexes
-- and 20260601000000_add_usercontent_trgm_index. They cannot be expressed in
-- schema.prisma (`USING GIN (... gin_trgm_ops)`), so Prisma sees them as drift
-- and proposes dropping them in every generated migration. SearchService ranks
-- with `similarity()` over both columns, so applying those drops would silently
-- degrade /search to sequential scans.

-- CreateTable
CREATE TABLE "_UserContentTags" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_UserContentTags_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateIndex
CREATE INDEX "_UserContentTags_B_index" ON "_UserContentTags"("B");

-- AddForeignKey
ALTER TABLE "_UserContentTags" ADD CONSTRAINT "_UserContentTags_A_fkey" FOREIGN KEY ("A") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_UserContentTags" ADD CONSTRAINT "_UserContentTags_B_fkey" FOREIGN KEY ("B") REFERENCES "UserContent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
