# Tolgee CLI configuration — dev environment
# Docs: https://tolgee.io/tolgee-cli/project-configuration
apiUrl: http://localhost:8085
projectId: 1

push:
  filesTemplate:
    - packages/shared/i18n/{languageTag}.json
    - packages/shared/i18n/{namespace}/{languageTag}.json

pull:
  path: packages/shared/i18n
  fileStructureTemplate: '{namespace}/{languageTag}.json'
