version: "3"
services:
  backend:
    build:
      context: ./apps/backend
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./apps/frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

  maildev:
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
