services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/backend
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - '3000:3000'
  frontend:
    build:
      context: ./apps/frontend
    depends_on:
      - backend
    ports:
      - '80:80'
