/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormFloatingLabel: typeof import('bootstrap-vue-next/components/BForm')['BFormFloatingLabel']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelectOption']
    BInput: typeof import('bootstrap-vue-next/components/BFormInput')['BInput']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BPlaceholderCard: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderCard']
    BPlaceholderWrapper: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderWrapper']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    ImageCarousel: typeof import('./src/components/profiles/public/ImageCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
