/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCarouselSlide: typeof import('bootstrap-vue-next/components/BCarousel')['BCarouselSlide']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
    BDropdownForm: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownForm']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
    BFormFloatingLabel: typeof import('bootstrap-vue-next/components/BForm')['BFormFloatingLabel']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInput: typeof import('bootstrap-vue-next/components/BFormInput')['BInput']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BPlaceholder: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholder']
    BPlaceholderCard: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderCard']
    BPlaceholderWrapper: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderWrapper']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BProgressBar: typeof import('bootstrap-vue-next/components/BProgress')['BProgressBar']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
    ImageCarousel: typeof import('./src/components/profiles/public/ImageCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
  const BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
  const BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
  const BCarouselSlide: typeof import('bootstrap-vue-next/components/BCarousel')['BCarouselSlide']
  const BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
  const BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
  const BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
  const BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
  const BDropdownForm: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownForm']
  const BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
  const BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
  const BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
  const BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
  const BFormFloatingLabel: typeof import('bootstrap-vue-next/components/BForm')['BFormFloatingLabel']
  const BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
  const BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
  const BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
  const BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
  const BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
  const BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
  const BFormSelectOption: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelectOption']
  const BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
  const BInput: typeof import('bootstrap-vue-next/components/BFormInput')['BInput']
  const BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
  const BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
  const BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
  const BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
  const BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
  const BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
  const BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
  const BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
  const BPlaceholder: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholder']
  const BPlaceholderCard: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderCard']
  const BPlaceholderWrapper: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderWrapper']
  const BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
  const BProgressBar: typeof import('bootstrap-vue-next/components/BProgress')['BProgressBar']
  const BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
  const BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
  const BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
  const ImageCarousel: typeof import('./src/components/profiles/public/ImageCarousel.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}