server {
  listen 3001;
  server_name localhost;

  root /var/www;
  index index.html;

  location = /sw.js {
    add_header Cache-Control "no-cache";
    try_files $uri =404;
  }

  location = /index.html {
    add_header Cache-Control "no-cache";
  }

  location = /assets/site.webmanifest {
    add_header Cache-Control "no-cache";
  }

  location /assets/ {
    add_header Cache-Control "public, max-age=43200";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
