name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.12.1
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate Prisma
        run: pnpm --filter backend exec npx prisma generate
      - name: Build frontend
        run: pnpm --filter frontend exec pnpm build
      - name: Backend tests
        run: pnpm --filter backend exec vitest run
      - name: Frontend unit tests
        run: pnpm --filter frontend exec vitest run --mode test
        
